### ISSUE TITLE
Trang xác nhận tài khoản thành công

### ISSUE THREAD

**Issue by vinaghost** [vinaghost/QLDA_Chieu_T4_02#39]
- [x] Trang xác nhận tài khoản thành công (@TranMinhThien9 )
- [x] Thêm xử lí request - paramhost khi đăng kí (@ngthotuan )

**Comment by TranMinhThien9** [comment]
hoàn thành frontend trang xác nhận

**Comment by ngthotuan** [comment]
https://api.vtsign.tech/auth/register -> https://api.vtsign.tech/auth/register2
https://api.vtsign.tech/document/signing -> https://api.vtsign.tech/document/signing2
các tham số và các api còn lại vẫn giữ nguyên
