### ISSUE TITLE
cập nhật api

### ISSUE THREAD

**Issue by ngthotuan** [vinaghost/QLDA_Chieu_T4_02#47]
https://api.vtsign.tech/auth/register -> https://api.vtsign.tech/auth/register2
https://api.vtsign.tech/document/signing -> https://api.vtsign.tech/document/signing2
các tham số và các api còn lại vẫn giữ nguyên

**Comment by vinaghost** [comment]
@quochiep99 anh sửa giúp e rồi tạo pull request trong lúc chờ e xem cái kia nhé
