### ISSUE TITLE
release file

### ISSUE THREAD

**Issue by vinaghost** [vinaghost/QLDA_Chieu_T4_02#53]
- [x] các file docker-compose.yml từng service @ngthotuan 
- [x] sửa đường dẫn api @tuan2012

**Comment by ngthotuan** [comment]
các file docker-compose.yml từng service: https://drive.google.com/file/d/1GeeATg1cRE1IXZYa6FcRtYVjGye1PxUz/view?usp=sharing

**Comment by tuan2012** [comment]
update backend nhánh feature/backend

**Comment by vinaghost** [comment]
@tuan2012  tạo pr luôn a ei
